### ISSUE TITLE
Small nitpicks

### ISSUE THREAD

**Issue by b-t-k** [drgrigg/wilkie-collins_the-dead-secret#1]
I got a change to images/cover.source.jpg when I ran build-images which is a new one for me. I don't think it meant anything, but you might check.

**content.opf**
- Does the long desc need to link to *The Woman in White* twice?

The following have semicolons inside quotes. Chicago says no and I can't see anything in the SEMOS that suggests we put them inside the quote.

**chapter-2-3**
- “Never mind about ‘some people;’ 

**chapter—4-1**
- It’s a song they call ‘Batti, Batti;’
- and Sarah’s joy is my joy;’

**chapter—6-1**
- directed to ‘<abbr epub:type="z3998:personal-name">S. J.</abbr>;’ to deliver 

**chapter—6-3**
- I dare not see her till she knows⁠—;’ 
- ⁠—‘The horses! I want to ride;’

**Comment by drgrigg** [comment]
I’ve never understood the (IMHO) weird American rule about putting punctuation inside rather than outside quotes. If semicolons aren’t to be treated that way, which punctuation marks are, other than periods and commas? And why on earth isn't it consistent?

Anyway, if we're following the Chicago Manual of Style then I guess I'll change them, but it doesn't stop me grumbling!

I also don't understand why build-images made a change to cover.source.jpg, though I think there might have been something mentioned about it, maybe to reduce the total image size for the repository? Anyway, I've accepted and pushed the change.

About the long description: because "Hide and Seek" isn't yet in our catalog, I've decided to take the link to Woman in White out there, making it look more consistent visually, but leaving it in the later reference where I mention both WiW and Moonstone, which are both in the catalog. Alex may have another view, of course!

**Comment by b-t-k** [comment]
Training-wise the rule about punctuation and quotes was entirely aesthetic. As a typographer a colon or semicolon looks clunky inside a quote (and a question mark would look downright bloated), while a comma or period outside a quote looks a bit lost and needs to snuggle up to something.

At least that's why I notice them :-)
